Resources:
  SuperUserIAM:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: 'POCDemoSuperUser'
      
  SuperUserIAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties: 
      Description: 'POC policy with full access'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      
  PolicyAttachment:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: !Ref SuperUserIAMPolicy
      Users: 
        - !Ref SuperUserIAM
